<?php

namespace Database\Factories\Concerns;

use Illuminate\Support\Facades\Storage;

trait CreatesPlaceholderPdf
{
    protected static function storePlaceholderPdf(string $path, string $title): int
    {
        $content = self::buildPdfDocument($title);

        Storage::disk('public')->put($path, $content);

        return strlen($content);
    }

    protected static function buildPdfDocument(string $title): string
    {
        $safeTitle = self::escapePdfText(self::sanitizePdfText($title));
        $stream = "BT\n/F1 18 Tf\n50 750 Td\n({$safeTitle}) Tj\n0 -28 Td\n/F1 11 Tf\n(Legal demo record generated by seeder) Tj\nET";

        $objects = [
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n",
            "4 0 obj\n<< /Length " . strlen($stream) . " >>\nstream\n{$stream}\nendstream\nendobj\n",
            "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
        ];

        $pdf = "%PDF-1.4\n";
        $offsets = [0];

        foreach ($objects as $object) {
            $offsets[] = strlen($pdf);
            $pdf .= $object;
        }

        $xrefOffset = strlen($pdf);

        $pdf .= "xref\n0 6\n0000000000 65535 f \n";

        for ($index = 1; $index <= 5; $index++) {
            $pdf .= sprintf("%010d 00000 n \n", $offsets[$index]);
        }

        $pdf .= "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }

    protected static function sanitizePdfText(string $value): string
    {
        $ascii = preg_replace('/[^A-Za-z0-9 .,:#\\/-]/', ' ', $value);
        $ascii = preg_replace('/\s+/', ' ', trim((string) $ascii));

        return $ascii !== '' ? substr($ascii, 0, 70) : 'Legal demo record';
    }

    protected static function escapePdfText(string $value): string
    {
        return str_replace(
            ['\\', '(', ')'],
            ['\\\\', '\\(', '\\)'],
            $value
        );
    }
}
