<?php
// Variables
return [
  "creatorName" => "Mohamed Atef",
  "creatorUrl" => "https://www.linkedin.com/in/moateflawyer/",
  "templateName" => "الإدارة القانونية",
  "templateSuffix" => "Legal Management",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Start your development with a Dashboard for Bootstrap 5",
  "templateKeyword" => "dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5",
  "licenseUrl" => "https://github.com/matef-hub",
  "livePreview" => "https://demos.pixinvent.com/vuexy-html-laravel-admin-template/demo-1/",
  "productPage" => "https://github.com/matef-hub/atef/blob/main/README.md",
  "support" => "https://www.linkedin.com/in/moateflawyer/",
  "moreThemes" => "https://themeforest.net/user/pixinvent/portfolio",
  "ogTitle" => "Vuexy bootstrap Dashboard by Pixinvent",
  "ogImage" => "https://pixinvent.com/wp-content/uploads/2023/06/vuexy-hero-image.png",
  "ogType" => "product",
  "documentation" => "https://github.com/matef-hub/atef/blob/main/README.md",
  "generator" => "",
  "changelog" => "https://demos.pixinvent.com/vuexy/changelog.html",
  "repository" => "https://github.com/matef-hub/atef/tree/main",
  "gitRepo" => "vuexy-html-laravel-admin-template",
  "gitRepoAccess" => "https://tools.pixinvent.com/github/github-access",
  "githubFreeUrl" => "https://github.com/pixinvent",
  "facebookUrl" => "https://www.facebook.com/pixinvents/",
  "twitterUrl" => "https://x.com/pixinvents",
  "githubUrl" => "https://github.com/pixinvent",
  "dribbbleUrl" => "https://dribbble.com/pixinvent",
  "instagramUrl" => "https://www.instagram.com/pixinvents/"
];
